video_url: "https://rtmp.ruangkitastudio.com/memfs/xxx.m3u8"
model_path: "best.engine"
rtsp_output_port: 8554
# db:
host: "103.115.164.119"
user: "vehilce_count"
password: "HPGnjLGGM6abndKp"
database: "vehilce_count"